
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.compi1.nodepad.scannerFiles.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ITEM_NUM = 12;
  public static final int INIT_LIST = 11;
  public static final int ITALIC_BOLD = 10;
  public static final int ITALIC = 8;
  public static final int EOF = 0;
  public static final int BREAKLINE = 15;
  public static final int BOLD = 9;
  public static final int H6 = 7;
  public static final int SENTENCE = 14;
  public static final int H5 = 6;
  public static final int error = 1;
  public static final int H4 = 5;
  public static final int H3 = 4;
  public static final int H2 = 3;
  public static final int ITEM_LIST = 13;
  public static final int H1 = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "H1",
  "H2",
  "H3",
  "H4",
  "H5",
  "H6",
  "ITALIC",
  "BOLD",
  "ITALIC_BOLD",
  "INIT_LIST",
  "ITEM_NUM",
  "ITEM_LIST",
  "SENTENCE",
  "BREAKLINE"
  };
}

